# lightning.pytorch==2.5.1
seed_everything: 0
trainer:
  log_every_n_steps: 400
  max_epochs: 25
model:
  class_path: FeatureDecoder
  init_args:
    feature_extractor:
      class_path: DinoFeatureExtractor
      init_args:
        out_features: ["stage2", "stage5", "stage8", "stage11"]
    decoder:
      class_path: UNetDecoder
      init_args:
        feature_shape: [3072, 30, 40] # 3'072 = 4 * 768 feature channels
    loss_fns:
      - - class_path: L2Loss
          init_args: { }
        - 1.0
data:
  data_root: data
  batch_size: 12
  num_workers: 16
  persistent_workers: true
  pin_memory: true
ckpt_path: null
